1.Run the code in this section. Change the conditional statement X == Y in this section to X < Y or X > Y, and then see what kind of tensor you can get.

In [2]:
import torch

In [3]:
X = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
Y = torch.tensor([[4,4,4],[5,5,5],[6,6,6]])

X,Y

(tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]),
 tensor([[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]))

In [4]:
X == Y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [5]:
X < Y

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [8]:
X > Y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [30]:
##a = torch.arange(0, 5, dtype =torch.float32)
##b = torch.arange(0, 4)

a = torch.arange(5, dtype = torch.float32).reshape((5,1))
b = torch.arange(5).reshape((1, 5))

a,b

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.]]),
 tensor([[0, 1, 2, 3, 4]]))

In [33]:
print('\n a + b = ', a + b)
print('\n a - b = ', a - b)
print('\n a * b = ', a * b)
print('\n a / b = ', a // b)


 a + b =  tensor([[0., 1., 2., 3., 4.],
        [1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.],
        [3., 4., 5., 6., 7.],
        [4., 5., 6., 7., 8.]])

 a - b =  tensor([[ 0., -1., -2., -3., -4.],
        [ 1.,  0., -1., -2., -3.],
        [ 2.,  1.,  0., -1., -2.],
        [ 3.,  2.,  1.,  0., -1.],
        [ 4.,  3.,  2.,  1.,  0.]])

 a * b =  tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.],
        [ 0.,  2.,  4.,  6.,  8.],
        [ 0.,  3.,  6.,  9., 12.],
        [ 0.,  4.,  8., 12., 16.]])

 a / b =  tensor([[nan, 0., 0., 0., 0.],
        [inf, 1., 0., 0., 0.],
        [inf, 2., 1., 0., 0.],
        [inf, 3., 1., 1., 0.],
        [inf, 4., 2., 1., 1.]])
